# Hello world STAGE server!

- name: Prepare environment
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Upgrade apt packages
      apt:
        upgrade: yes
  
    
# [ Role executions ]
    
- name: Deploy FRONTEND application
  hosts: servers
  become: yes
  vars:
    app_name: "vm-api"
    app_port: 3000
    
  roles:
    - role: ../../roles/nodejs
    
    - role: ../../roles/app
      vars:     
        app_repo_url: "https://github.com/austinbrage/brage-js-sample.git"
        app_repo_branch: "main"
        run_npm_install: true
        run_npm_build: false
        
    - role: ../../roles/nginx
      vars: 
        subdomain: "www"
        server_domain: "mydomain.com"
