---

- name: Save PM2 process list
  shell: pm2 save

- name: Configure PM2 startup on boot
  shell: pm2 startup
  register: pm2_startup_output

- name: Execute PM2 startup command
  shell: "{{ pm2_startup_output.stdout | regex_replace('^.*sudo', 'sudo') }}" 